const { v4: uuidv4 } = require("uuid");

const products = [
  {
    brand: "Nike",
    category: "Case Cover",
    discount: 50,
    fastDelivery: true,
    image:
      "https://footballmonk.in/wp-content/uploads/2021/02/FC-Barcelona-Home-Jersey-Case-Cover-Customisable-1.jpg",
    inStock: true,
    name: "FC Barcelona Home Jersey Case Cover",
    price: 249,
  },
  {
    brand: "Adidas",
    category: "Case Cover",
    discount: 50,
    fastDelivery: false,
    image:
      "https://footballmonk.in/wp-content/uploads/2021/02/Juventus20Home20Jersey20Case20Cover20Customisable201.jpg",
    inStock: true,
    name: "Juventus Home Jersey Case Cover",
    price: 249,
  },
  {
    brand: "Nike",
    category: "Case Cover",
    discount: 50,
    fastDelivery: true,
    image:
      "https://footballmonk.in/wp-content/uploads/2021/02/PSG20Home20Jersey20Case20Cover20Customisable201-600x600.jpg",
    inStock: true,
    name: "PSG Home Jersey Case Cover",
    price: 249,
  },
  {
    brand: "Adidas",
    category: "Case Cover",
    discount: 50,
    fastDelivery: false,
    image:
      "https://footballmonk.in/wp-content/uploads/2021/02/Real20Madrid20Third20Jersey20Case20Cover20Customisable201.jpg",
    inStock: true,
    name: "Real Madrid Third Jersey Case Cover",
    price: 249,
  },
  {
    brand: "Nike",
    category: "Case Cover",
    discount: 50,
    fastDelivery: true,
    image:
      "https://footballmonk.in/wp-content/uploads/2021/02/Chelsea20Away20Jersey20Case20Cover20Cusotmisable201.jpg",
    inStock: true,
    name: "Chelsea Away Jersey Case Cover",
    price: 249,
  },
  {
    brand: "Adidas",
    category: "Case Cover",
    discount: 50,
    fastDelivery: false,
    image:
      "https://footballmonk.in/wp-content/uploads/2021/02/Bayern20Munich20Home20Jersey20Case20Cover20Customisable201-600x599.jpg",
    inStock: true,
    name: "Bayern Munich Home Jersey Case Cover",
    price: 249,
  },
  {
    brand: "Nike",
    category: "Case Cover",
    discount: 50,
    fastDelivery: true,
    image:
      "https://footballmonk.in/wp-content/uploads/2021/02/Atletico20Madrid20Away20Jersey20Case20Cover20Customisable201.jpg",
    inStock: true,
    name: "Atletico Madrid Away Jersey Case Cover",
    price: 249,
  },
  {
    brand: "Adidas",
    category: "Case Cover",
    discount: 50,
    fastDelivery: false,
    image:
      "https://footballmonk.in/wp-content/uploads/2021/02/Manchester20United20Home20Jersey20Case20Cover20Customisable201-600x600.jpg",
    inStock: true,
    name: "Manchester United Home Jersey Case Cover",
    price: 249,
  },
  {
    brand: "Nike",
    category: "Case Cover",
    discount: 50,
    fastDelivery: true,
    image:
      "https://footballmonk.in/wp-content/uploads/2021/02/Liverpool20Home20Jersey20Case20Cover20Customisable201-600x600.jpg",
    inStock: true,
    name: "Liverpool Home Jersey Case Cover",
    price: 249,
  },
  {
    brand: "Adidas",
    category: "Case Cover",
    discount: 50,
    fastDelivery: false,
    image:
      "https://footballmonk.in/wp-content/uploads/2021/02/Arsenal20Away20Jersey20Case20Cover20Customisable201.jpg",
    inStock: false,
    name: "Arsenal Away Jersey Case Cover",
    price: 249,
  },
  {
    brand: "Nike",
    category: "Case Cover",
    discount: 50,
    fastDelivery: false,
    image:
      "https://footballmonk.in/wp-content/uploads/2021/02/Tottenham20HotSpur20Home20Jersey20Case20Cover20Customisable201.jpg",
    inStock: false,
    name: "Tottenham Hotspurs Home Jersey Case Cover",
    price: 249,
  },
  {
    brand: "Adidas",
    category: "Football",
    discount: 30,
    fastDelivery: false,
    image:
      "https://storage.sg.content-cdn.io/cdn-cgi/image/width=500,height=500,quality=75,format=auto,fit=cover,g=top/in-resources/b368029c-a4dd-448a-a888-58348cb1b144/Images/ProductImages/Source/ADCE8083.jpg",
    inStock: true,
    name: "Adidas FIFA World Cup 2018 Football",
    price: 1399,
  },
  {
    brand: "Nike",
    category: "Football",
    discount: 40,
    fastDelivery: true,
    image:
      "https://storage.sg.content-cdn.io/cdn-cgi/image/width=500,height=500,quality=75,format=auto,fit=cover,g=top/in-resources/b368029c-a4dd-448a-a888-58348cb1b144/Images/ProductImages/Source/NKSC3137-711.jpg",
    inStock: true,
    name: "Nike Premier League Football",
    price: 1099,
  },
  {
    brand: "Adidas",
    category: "Football",
    discount: 30,
    fastDelivery: false,
    image:
      "https://rukminim1.flixcart.com/image/612/612/ball/m/r/k/ap0487-22-450-1-adidas-football-real-madrid-original-imaemc684axcpwdx.jpeg?q=70",
    inStock: true,
    name: "Adidas Real Madrid Football",
    price: 1049,
  },
  {
    brand: "Nike",
    category: "Football",
    discount: 40,
    fastDelivery: true,
    image: "https://m.media-amazon.com/images/I/61ZZyPec4rL._AC_UL1000_.jpg",
    inStock: true,
    name: "Nike FC Barcelona Football",
    price: 799,
  },
  {
    brand: "Nike",
    category: "Football",
    discount: 30,
    fastDelivery: false,
    image:
      "https://cdn.kickscrew.com/media/catalog/product/cache/dd3ae58018643bb67b4bf8f0a77873b1/S/C/SC3981-610_Nike_PSG_Magia_Match_Soccer_Ball_Infrared_Black_a.jpg",
    inStock: true,
    name: "Nike PSG Football",
    price: 1399,
  },
  {
    brand: "Adidas",
    category: "Football",
    discount: 40,
    fastDelivery: true,
    image:
      "https://rukminim1.flixcart.com/image/612/612/kit6hzk0-0/ball/l/9/w/425-chelsea-football-club-football-blue-5-22-1-chelsea-football-original-imafygzhduax7q2r.jpeg?q=70",
    inStock: true,
    name: "Adidas Chelsea Football",
    price: 1099,
  },
  {
    brand: "Adidas",
    category: "Football",
    discount: 30,
    fastDelivery: false,
    image: "https://m.media-amazon.com/images/I/81yUxgVqwWL._AC_SL1500_.jpg",
    inStock: false,
    name: "Adidas FC Bayern Football",
    price: 1049,
  },
  {
    brand: "Nike",
    category: "Football",
    discount: 40,
    fastDelivery: true,
    image: "https://m.media-amazon.com/images/I/61FSybHWUOL._SL1100_.jpg",
    inStock: false,
    name: "Nike Liverpool Football",
    price: 799,
  },
  {
    brand: "Nike",
    category: "Goalie Gloves",
    discount: 10,
    fastDelivery: true,
    image:
      "https://storage.sg.content-cdn.io/cdn-cgi/image/width=500,height=500,quality=75,format=auto,fit=cover,g=top/in-resources/b368029c-a4dd-448a-a888-58348cb1b144/Images/ProductImages/Source/NKGS0331-657.jpg",
    inStock: true,
    name: "Nike GK Junior Goalkeeper Gloves",
    price: 1599,
  },
  {
    brand: "Adidas",
    category: "Goalie Gloves",
    discount: 60,
    fastDelivery: false,
    image:
      "https://storage.sg.content-cdn.io/cdn-cgi/image/width=500,height=500,quality=75,format=auto,fit=cover,g=top/in-resources/b368029c-a4dd-448a-a888-58348cb1b144/Images/ProductImages/Source/ADCW5611.jpg",
    inStock: true,
    name: "Adidas X Lite Goalkeeper Gloves",
    price: 799,
  },
  {
    brand: "Nike",
    category: "Goalie Gloves",
    discount: 20,
    fastDelivery: true,
    image: "https://m.media-amazon.com/images/I/61qIBk54GlS._UL1500_.jpg",
    inStock: true,
    name: "Nike Goalkeeper Gloves",
    price: 1299,
  },
  {
    brand: "Adidas",
    category: "Goalie Gloves",
    discount: 60,
    fastDelivery: true,
    image:
      "https://storage.sg.content-cdn.io/cdn-cgi/image/width=500,height=500,quality=75,format=auto,fit=cover,g=top/in-resources/b368029c-a4dd-448a-a888-58348cb1b144/Images/ProductImages/Source/ADM38623L.jpg",
    inStock: true,
    name: "Adidas Training Goalkeeper Gloves",
    price: 799,
  },
  {
    brand: "Nike",
    category: "Goalie Gloves",
    discount: 10,
    fastDelivery: false,
    image:
      "https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/e4dd0335-eeae-46d3-afeb-2af6f0424802/goalkeeper-match-football-gloves-0S4K6P.png",
    inStock: true,
    name: "Nike Match Goalkeeper Gloves",
    price: 1599,
  },
  {
    brand: "Adidas",
    category: "Goalie Gloves",
    discount: 50,
    fastDelivery: true,
    image:
      "https://storage.sg.content-cdn.io/cdn-cgi/image/width=500,height=500,quality=75,format=auto,fit=cover,g=top/in-resources/b368029c-a4dd-448a-a888-58348cb1b144/Images/ProductImages/Source/ADM38740L.jpg",
    inStock: false,
    name: "Adidas Training Goalkeeper Gloves",
    price: 799,
  },
  {
    brand: "Adidas",
    category: "Jersey",
    discount: 50,
    fastDelivery: true,
    image:
      "https://footballmonk.in/wp-content/uploads/2020/10/buy-argentina-away-jersey-20-21-online-india-1.jpg",
    inStock: true,
    name: "Argentina Away Jersey 20-21",
    price: 849,
  },
  {
    brand: "Nike",
    category: "Jersey",
    discount: 50,
    fastDelivery: false,
    image:
      "https://footballmonk.in/wp-content/uploads/2021/07/barcelona_home_kit_21_22-1-1.jpg",
    inStock: true,
    name: "Barcelona Home Kit 21-22",
    price: 999,
  },
  {
    brand: "Adidas",
    category: "Jersey",
    discount: 50,
    fastDelivery: true,
    image:
      "https://footballmonk.in/wp-content/uploads/2021/08/manchester-united-home-21-22-1.jpg",
    inStock: true,
    name: "Manchester United Home Kit 21-22",
    price: 999,
  },
  {
    brand: "Nike",
    category: "Jersey",
    discount: 50,
    fastDelivery: false,
    image:
      "https://footballmonk.in/wp-content/uploads/2021/07/Liverpool-away-kit-21-22-1.jpg",
    inStock: true,
    name: "Liverpool Away Kit 21-22",
    price: 849,
  },
  {
    brand: "Adidas",
    category: "Jersey",
    discount: 50,
    fastDelivery: true,
    image:
      "https://footballmonk.in/wp-content/uploads/2021/07/Bayern-Munich-away-kit-21-22-1.jpg",
    inStock: true,
    name: "Bayern Munich Away Kit 21-22",
    price: 999,
  },
  {
    brand: "Nike",
    category: "Jersey",
    discount: 50,
    fastDelivery: false,
    image:
      "https://footballmonk.in/wp-content/uploads/2021/07/Chelsea-Home-kit-21-22-1.jpg",
    inStock: true,
    name: "Chelsea Home Kit 21-22",
    price: 999,
  },
  {
    brand: "Adidas",
    category: "Jersey",
    discount: 50,
    fastDelivery: false,
    image:
      "https://footballmonk.in/wp-content/uploads/2021/07/Real-madrid-Home-kit-21-22-1.jpg",
    inStock: true,
    name: "Real Madrid Home Kit 21-22",
    price: 849,
  },
  {
    brand: "Nike",
    category: "Jersey",
    discount: 50,
    fastDelivery: true,
    image:
      "https://footballmonk.in/wp-content/uploads/2020/10/buy-france-home-jersey-20-21-online-in-india-1.jpg",
    inStock: true,
    name: "France Home Kit 20-21",
    price: 849,
  },
  {
    brand: "Adidas",
    category: "Jersey",
    discount: 50,
    fastDelivery: true,
    image:
      "https://footballmonk.in/wp-content/uploads/2021/07/Arsenal-Away-kit-21-22-1.jpg",
    inStock: false,
    name: "Arsenal Away Kit 21-22",
    price: 849,
  },
  {
    brand: "Nike",
    category: "Jersey",
    discount: 50,
    fastDelivery: true,
    image:
      "https://footballmonk.in/wp-content/uploads/2021/07/spurs-home-kit-21-22-1.jpg",
    inStock: false,
    name: "Tottenham Hotspurs Home Kit 21-22",
    price: 849,
  },
  {
    brand: "Nike",
    category: "Shin Guards",
    discount: 50,
    fastDelivery: true,
    image:
      "https://storage.sg.content-cdn.io/cdn-cgi/image/width=500,height=500,quality=75,format=auto,fit=cover,g=top/in-resources/b368029c-a4dd-448a-a888-58348cb1b144/Images/ProductImages/Source/NKSP2093-451L.jpg",
    inStock: true,
    name: "Nike Protegga Flex Shin Guard",
    price: 999,
  },
  {
    brand: "Adidas",
    category: "Shin Guards",
    discount: 50,
    fastDelivery: false,
    image:
      "https://storage.sg.content-cdn.io/cdn-cgi/image/width=500,height=500,quality=75,format=auto,fit=cover,g=top/in-resources/b368029c-a4dd-448a-a888-58348cb1b144/Images/ProductImages/Source/ADBR5366.jpg",
    inStock: true,
    name: "Adidas Ghost Letto Shin Guard",
    price: 749,
  },
  {
    brand: "Nike",
    category: "Shin Guards",
    discount: 50,
    fastDelivery: false,
    image:
      "https://storage.sg.content-cdn.io/cdn-cgi/image/width=500,height=500,quality=75,format=auto,fit=cover,g=top/in-resources/b368029c-a4dd-448a-a888-58348cb1b144/Images/ProductImages/Source/NKSP0313-451.jpg",
    inStock: true,
    name: "Nike Charge 2.0 Shin Guard",
    price: 999,
  },
  {
    brand: "Adidas",
    category: "Shin Guards",
    discount: 50,
    fastDelivery: true,
    image:
      "https://storage.sg.content-cdn.io/cdn-cgi/image/width=500,height=500,quality=75,format=auto,fit=cover,g=top/in-resources/b368029c-a4dd-448a-a888-58348cb1b144/Images/ProductImages/Source/ADCW9716.jpg",
    inStock: true,
    name: "Adidas X Lesto Shin Guard",
    price: 749,
  },
  {
    brand: "Nike",
    category: "Shin Guards",
    discount: 50,
    fastDelivery: true,
    image:
      "https://storage.sg.content-cdn.io/cdn-cgi/image/width=500,height=500,quality=75,format=auto,fit=cover,g=top/in-resources/b368029c-a4dd-448a-a888-58348cb1b144/Images/ProductImages/Source/NKSP2086-876.jpg",
    inStock: true,
    name: "Nike Mercurial Lite Shin Guard",
    price: 999,
  },
  {
    brand: "Adidas",
    category: "Shin Guards",
    discount: 50,
    fastDelivery: false,
    image:
      "https://storage.sg.content-cdn.io/cdn-cgi/image/width=500,height=500,quality=75,format=auto,fit=cover,g=top/in-resources/b368029c-a4dd-448a-a888-58348cb1b144/Images/ProductImages/Source/ADCW5561.jpg",
    inStock: false,
    name: "Adidas Everlesto Shin Guard",
    price: 749,
  },
  {
    brand: "Adidas",
    category: "Shoes",
    discount: 40,
    fastDelivery: true,
    image:
      "https://storage.sg.content-cdn.io/cdn-cgi/image/width=500,height=500,quality=75,format=auto,fit=cover,g=top/in-resources/b368029c-a4dd-448a-a888-58348cb1b144/Images/ProductImages/Source/ADFSB44253L.jpg",
    inStock: true,
    name: "Adidas Nitrocharge 3.0 Football Shoes",
    price: 2399,
  },
  {
    brand: "Nike",
    category: "Shoes",
    discount: 30,
    fastDelivery: false,
    image:
      "https://storage.sg.content-cdn.io/cdn-cgi/image/width=500,height=500,quality=75,format=auto,fit=cover,g=top/in-resources/b368029c-a4dd-448a-a888-58348cb1b144/Images/ProductImages/Source/NK852494-001.jpg",
    inStock: true,
    name: "Nike Mercurial Football Shoes",
    price: 2099,
  },
  {
    brand: "Adidas",
    category: "Shoes",
    discount: 30,
    fastDelivery: true,
    image:
      "https://storage.sg.content-cdn.io/cdn-cgi/image/width=500,height=500,quality=75,format=auto,fit=cover,g=top/in-resources/b368029c-a4dd-448a-a888-58348cb1b144/Images/ProductImages/Source/ADFSAQ3526.jpg",
    inStock: true,
    name: "Adidas X Messi 16.4 FXG Football Shoes",
    price: 1749,
  },
  {
    brand: "Nike",
    category: "Shoes",
    discount: 40,
    fastDelivery: false,
    image:
      "https://storage.sg.content-cdn.io/cdn-cgi/image/width=500,height=500,quality=75,format=auto,fit=cover,g=top/in-resources/b368029c-a4dd-448a-a888-58348cb1b144/Images/ProductImages/Source/NK744943-080L.jpg",
    inStock: true,
    name: "Nike Hypervenom Phelon II FG Junior Football Shoes",
    price: 2399,
  },
  {
    brand: "Adidas",
    category: "Shoes",
    discount: 30,
    fastDelivery: true,
    image:
      "https://storage.sg.content-cdn.io/cdn-cgi/image/width=500,height=500,quality=75,format=auto,fit=cover,g=top/in-resources/b368029c-a4dd-448a-a888-58348cb1b144/Images/ProductImages/Source/ADFSS77090.jpg",
    inStock: true,
    name: "Adidas ACE 17.4 FXG Football Shoes",
    price: 2099,
  },
  {
    brand: "Nike",
    category: "Shoes",
    discount: 30,
    fastDelivery: true,
    image:
      "https://storage.sg.content-cdn.io/cdn-cgi/image/width=500,height=500,quality=75,format=auto,fit=cover,g=top/in-resources/b368029c-a4dd-448a-a888-58348cb1b144/Images/ProductImages/Source/NK844436-417.jpg",
    inStock: true,
    name: "Nike Bravata II FG Football Shoes",
    price: 1749,
  },
  {
    brand: "Adidas",
    category: "Shoes",
    discount: 40,
    fastDelivery: false,
    image:
      "https://storage.sg.content-cdn.io/cdn-cgi/image/width=500,height=500,quality=75,format=auto,fit=cover,g=top/in-resources/b368029c-a4dd-448a-a888-58348cb1b144/Images/ProductImages/Source/ADFSS42139.jpg",
    inStock: true,
    name: "Adidas ACE 16.4 FXG Football Shoes",
    price: 2399,
  },
  {
    brand: "Nike",
    category: "Shoes",
    discount: 30,
    fastDelivery: true,
    image:
      "https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/b2dd77f3-5c14-4fa1-8687-d3c1908fd6a6/mercurial-vapor-14-club-fg-mg-multi-ground-football-boot-t74W26.png",
    inStock: true,
    name: "Nike Mercurial Vapor 14 Football Shoes",
    price: 2099,
  },
  {
    brand: "Adidas",
    category: "Shoes",
    discount: 30,
    fastDelivery: true,
    image:
      "https://storage.sg.content-cdn.io/cdn-cgi/image/width=500,height=500,quality=75,format=auto,fit=cover,g=top/in-resources/b368029c-a4dd-448a-a888-58348cb1b144/Images/ProductImages/Source/ADFSS74689.jpg",
    inStock: false,
    name: "Adidas Messi 15.3 Football Shoes",
    price: 1749,
  },
  {
    brand: "Adidas",
    category: "Shoes",
    discount: 40,
    fastDelivery: false,
    image:
      "https://storage.sg.content-cdn.io/cdn-cgi/image/width=500,height=500,quality=75,format=auto,fit=cover,g=top/in-resources/b368029c-a4dd-448a-a888-58348cb1b144/Images/ProductImages/Source/NK749896-888L.jpg",
    inStock: false,
    name: "Nike Hypervenom Phelon II FG Football Shoes",
    price: 2399,
  },
];
